export const departamentos = [
  { id: 'amazonas', nombre: 'Amazonas' },
  { id: 'antioquia', nombre: 'Antioquia' },
  { id: 'arauca', nombre: 'Arauca' },
  { id: 'atlantico', nombre: 'Atlántico' },
  { id: 'bolivar', nombre: 'Bolívar' },
  { id: 'boyaca', nombre: 'Boyacá' },
  { id: 'caldas', nombre: 'Caldas' },
  { id: 'caqueta', nombre: 'Caquetá' },
  { id: 'casanare', nombre: 'Casanare' },
  { id: 'cauca', nombre: 'Cauca' },
  { id: 'cesar', nombre: 'Cesar' },
  { id: 'choco', nombre: 'Chocó' },
  { id: 'cordoba', nombre: 'Córdoba' },
  { id: 'cundinamarca', nombre: 'Cundinamarca' },
  { id: 'guainia', nombre: 'Guainía' },
  { id: 'guaviare', nombre: 'Guaviare' },
  { id: 'huila', nombre: 'Huila' },
  { id: 'la_guajira', nombre: 'La Guajira' },
  { id: 'magdalena', nombre: 'Magdalena' },
  { id: 'meta', nombre: 'Meta' },
  { id: 'nariño', nombre: 'Nariño' },
  { id: 'norte_de_santander', nombre: 'Norte de Santander' },
  { id: 'putumayo', nombre: 'Putumayo' },
  { id: 'quindio', nombre: 'Quindío' },
  { id: 'risaralda', nombre: 'Risaralda' },
  { id: 'san_andres', nombre: 'San Andrés y Providencia' },
  { id: 'santander', nombre: 'Santander' },
  { id: 'sucre', nombre: 'Sucre' },
  { id: 'tolima', nombre: 'Tolima' },
  { id: 'valle_del_cauca', nombre: 'Valle del Cauca' },
  { id: 'vaupes', nombre: 'Vaupés' },
  { id: 'vichada', nombre: 'Vichada' },
  { id: 'bogota_dc', nombre: 'Bogotá D.C.' },
];

export const ciudades: { [key: string]: { id: string, nombre: string }[] } = {
  amazonas: [
    { id: 'leticia', nombre: 'Leticia' },
    { id: 'puerto_nariño', nombre: 'Puerto Nariño' },
  ],
  antioquia: [
    { id: 'medellin', nombre: 'Medellín' },
    { id: 'bello', nombre: 'Bello' },
    { id: 'envigado', nombre: 'Envigado' },
    { id: 'itagui', nombre: 'Itagüí' },
    { id: 'apartado', nombre: 'Apartadó' },
    { id: 'turbo', nombre: 'Turbo' },
    { id: 'rionegro', nombre: 'Rionegro' },
    { id: 'la_estrella', nombre: 'La Estrella' },
    { id: 'caldas', nombre: 'Caldas' },
    { id: 'copacabana', nombre: 'Copacabana' },
  ],
  arauca: [
    { id: 'arauca', nombre: 'Arauca' },
    { id: 'saravena', nombre: 'Saravena' },
    { id: 'tame', nombre: 'Tame' },
  ],
  atlantico: [
    { id: 'barranquilla', nombre: 'Barranquilla' },
    { id: 'soledad', nombre: 'Soledad' },
    { id: 'malambo', nombre: 'Malambo' },
    { id: 'puerto_colombia', nombre: 'Puerto Colombia' },
    { id: 'galapa', nombre: 'Galapa' },
  ],
  bolivar: [
    { id: 'cartagena', nombre: 'Cartagena' },
    { id: 'magangue', nombre: 'Magangué' },
    { id: 'turbo', nombre: 'Turbo' },
    { id: 'arroyohondo', nombre: 'Arroyohondo' },
    { id: 'santa_catalina', nombre: 'Santa Catalina' },
  ],
  boyaca: [
    { id: 'tunja', nombre: 'Tunja' },
    { id: 'duitama', nombre: 'Duitama' },
    { id: 'sogamoso', nombre: 'Sogamoso' },
    { id: 'chiquinquira', nombre: 'Chiquinquirá' },
    { id: 'paipa', nombre: 'Paipa' },
  ],
  caldas: [
    { id: 'manizales', nombre: 'Manizales' },
    { id: 'villamaria', nombre: 'Villamaría' },
    { id: 'chinchina', nombre: 'Chinchiná' },
    { id: 'riosucio', nombre: 'Riosucio' },
  ],
  caqueta: [
    { id: 'florencia', nombre: 'Florencia' },
    { id: 'san_vicente_del_caguan', nombre: 'San Vicente del Caguán' },
    { id: 'puerto_rico', nombre: 'Puerto Rico' },
  ],
  casanare: [
    { id: 'yopal', nombre: 'Yopal' },
    { id: 'aguazul', nombre: 'Aguazul' },
    { id: 'villanueva', nombre: 'Villanueva' },
    { id: 'mani', nombre: 'Maní' },
  ],
  cauca: [
    { id: 'popayan', nombre: 'Popayán' },
    { id: 'santander_de_quilichao', nombre: 'Santander de Quilichao' },
    { id: 'puente_nacional', nombre: 'Puente Nacional' },
    { id: 'patia', nombre: 'Patía' },
  ],
  cesar: [
    { id: 'valledupar', nombre: 'Valledupar' },
    { id: 'aguachica', nombre: 'Aguachica' },
    { id: 'bosconia', nombre: 'Bosconia' },
    { id: 'curumani', nombre: 'Curumaní' },
  ],
  choco: [
    { id: 'quibdo', nombre: 'Quibdó' },
    { id: 'istmina', nombre: 'Istmina' },
    { id: 'condoto', nombre: 'Condoto' },
    { id: 'nuqui', nombre: 'Nuquí' },
  ],
  cordoba: [
    { id: 'monteria', nombre: 'Montería' },
    { id: 'cerete', nombre: 'Cereté' },
    { id: 'lorica', nombre: 'Lorica' },
    { id: 'sahagun', nombre: 'Sahagún' },
  ],
  cundinamarca: [
    { id: 'bogota', nombre: 'Bogotá' },
    { id: 'soacha', nombre: 'Soacha' },
    { id: 'zipaquira', nombre: 'Zipaquirá' },
    { id: 'facatativa', nombre: 'Facatativá' },
    { id: 'choconta', nombre: 'Chocontá' },
  ],
  guainia: [
    { id: 'inirida', nombre: 'Inírida' },
    { id: 'barranco_minas', nombre: 'Barranco Minas' },
  ],
  guaviare: [
    { id: 'san_jose_del_guaviare', nombre: 'San José del Guaviare' },
    { id: 'calamar', nombre: 'Calamar' },
    { id: 'miraflores', nombre: 'Miraflores' },
  ],
  huila: [
    { id: 'neiva', nombre: 'Neiva' },
    { id: 'pitalito', nombre: 'Pitalito' },
    { id: 'garzon', nombre: 'Garzón' },
    { id: 'la_plata', nombre: 'La Plata' },
  ],
  la_guajira: [
    { id: 'riohacha', nombre: 'Riohacha' },
    { id: 'maicao', nombre: 'Maicao' },
    { id: 'uribia', nombre: 'Uribia' },
    { id: 'albania', nombre: 'Albania' },
  ],
  magdalena: [
    { id: 'santa_marta', nombre: 'Santa Marta' },
    { id: 'ciudadela', nombre: 'Ciénaga' },
    { id: 'fundacion', nombre: 'Fundación' },
    { id: 'aracataca', nombre: 'Aracataca' },
  ],
  meta: [
    { id: 'villavicencio', nombre: 'Villavicencio' },
    { id: 'granada', nombre: 'Granada' },
    { id: 'acacias', nombre: 'Acacías' },
    { id: 'puerto_lopez', nombre: 'Puerto López' },
  ],
  nariño: [
    { id: 'pasto', nombre: 'Pasto' },
    { id: 'tumaco', nombre: 'Tumaco' },
    { id: 'ipiales', nombre: 'Ipiales' },
    { id: 'tuquerres', nombre: 'Túquerres' },
  ],
  norte_de_santander: [
    { id: 'cucuta', nombre: 'Cúcuta' },
    { id: 'ocaña', nombre: 'Ocaña' },
    { id: 'villa_del_rosario', nombre: 'Villa del Rosario' },
    { id: 'pamplona', nombre: 'Pamplona' },
  ],
  putumayo: [
    { id: 'mocoa', nombre: 'Mocoa' },
    { id: 'puerto_asís', nombre: 'Puerto Asís' },
    { id: 'orito', nombre: 'Orito' },
    { id: 'sibundoy', nombre: 'Sibundoy' },
  ],
  quindio: [
    { id: 'armenia', nombre: 'Armenia' },
    { id: 'calarca', nombre: 'Calarcá' },
    { id: 'quimbaya', nombre: 'Quimbaya' },
    { id: 'montenegro', nombre: 'Montenegro' },
  ],
  risaralda: [
    { id: 'pereira', nombre: 'Pereira' },
    { id: 'dosquebradas', nombre: 'Dosquebradas' },
    { id: 'santa_rosa_de_cabal', nombre: 'Santa Rosa de Cabal' },
    { id: 'la_virginia', nombre: 'La Virginia' },
  ],
  san_andres: [
    { id: 'san_andres', nombre: 'San Andrés' },
    { id: 'providencia', nombre: 'Providencia' },
  ],
  santander: [
    { id: 'bucaramanga', nombre: 'Bucaramanga' },
    { id: 'floridablanca', nombre: 'Floridablanca' },
    { id: 'girardot', nombre: 'Girardot' },
    { id: 'piedecuesta', nombre: 'Piedecuesta' },
  ],
  sucre: [
    { id: 'sincelejo', nombre: 'Sincelejo' },
    { id: 'corozal', nombre: 'Corozal' },
    { id: 'toluviejo', nombre: 'Toluviejo' },
    { id: 'sampues', nombre: 'Sampués' },
  ],
  tolima: [
    { id: 'ibague', nombre: 'Ibagué' },
    { id: 'espinal', nombre: 'Espinal' },
    { id: 'melgar', nombre: 'Melgar' },
    { id: 'chaparral', nombre: 'Chaparral' },
  ],
  valle_del_cauca: [
    { id: 'cali', nombre: 'Cali' },
    { id: 'palmira', nombre: 'Palmira' },
    { id: 'tulua', nombre: 'Tuluá' },
    { id: 'buga', nombre: 'Buga' },
    { id: 'yumbo', nombre: 'Yumbo' },
  ],
  vaupes: [
    { id: 'mitu', nombre: 'Mitú' },
    { id: 'caruru', nombre: 'Carurú' },
  ],
  vichada: [
    { id: 'puerto_carreno', nombre: 'Puerto Carreño' },
    { id: 'la_primavera', nombre: 'La Primavera' },
  ],
  bogota_dc: [
    { id: 'bogota', nombre: 'Bogotá' },
  ],
};

export const getCiudadesPorDepartamento = (idDepartamento: string) => {
  return ciudades[idDepartamento] || [];
};
